### ISSUE TITLE
Question about CLIP Semantic Similarity Calculation

### ISSUE THREAD

**Issue by wyn0630** [researchcode001/daca#1]
Dear author，
  I've been exploring your project.
  
  I'm curious why CLIP Semantic similarity is calculated specifically for images generated with the Re-use adversarial prompt but not for those generated with the One-time adversarial prompt. Could you please shed some light on this decision?

  Thanks for your time, and I appreciate your work on Divide-and-Conquer-Attack.
  
  Best wishes！

**Comment by researchcode001** [comment]
> Dear author， I've been exploring your project.
> 
> I'm curious why CLIP Semantic similarity is calculated specifically for images generated with the Re-use adversarial prompt but not for those generated with the One-time adversarial prompt. Could you please shed some light on this decision?
> 
> Thanks for your time, and I appreciate your work on Divide-and-Conquer-Attack.
> 
> Best wishes！

The purpose of calculating CLIP semantic similarity is to analyze the reasons behind DACA's success through comparing similarity between adversarial prompts and original prompts. Since we generate adversarial prompts through LLMs, adversarial prompts produced in the One-time process are sometimes unusable (e.g. "Sorry, we can't complete this task") or not worth analyzing (e.g. "A large amount of meaningless text"), we believe it's pointless to evaluate the semantic similarity of such prompts. On the other hand, Re-use prompts are filtered, relatively stable, and can at least successfully generate harmful images visually consistent with the original prompt's meaning (Manual Review). Analyzing the relationship between these adversarial prompts that can bypass safety filters and the original harmful prompts is valuable.

To conduct a comprehensive analysis, we carried out further experiments on the adversarial prompts in the one-time process: We divided the adversarial prompts obtained in One-time into three categories (Manual Review): the first category failed to bypass the safety filter, the second category's generated images do not contain harmful information, and the third category's generated images contain harmful information. We calculated the CLIP semantic similarity for each category of adversarial prompts (with GPT-4 as the backbone LLM). We found that, after excluding the meaningless prompts mentioned above, the overall trend of semantic similarity across the three categories decreases, with the first category's CLIP semantic similarity being slightly higher than the second, which in turn is slightly higher than the third. (Each category has some exceptions.)
By analyzing the content of adversarial prompts, we believe: 
1. Adversarial prompts containing rich harmful information that matches the original prompts exhibit higher semantic similarity, but prompts with too much and too explicit harmful information are easily blocked by safety filters.
2. The better the LLM is at deconstructing and rephrasing harmful information, the lower the semantic similarity of adversarial prompts compared to prompts with rich harmful content but blocked by safety filters.
3. High semantic similarity prompts does not imply they contain a sufficient amount of harmful information. The proportion of harmful information text within the total text of adversarial prompts is not high, just as the harmful elements in harmful images occupy only a small part of the image. There are some adversarial prompts that bypass the safety filter but generate harmless images. The reason these adversarial prompts have high semantic similarity is because the non-harmful part of their text is substantial and similar to the corresponding parts in the original samples.
Thank you for your interest in the DACA, and we hope this answers your question!
