### ISSUE TITLE
The results of the GPT-4 Image Review

### ISSUE THREAD

**Issue by wyn0630** [researchcode001/daca#2]
Dear author，
I hope this message finds you well. I have been examining your research on DACA.

I am particularly interested in understanding how the results of the GPT-4 Image Review methodology demonstrate high semantic similarity. I find it a bit unclear, and I would appreciate it if you could provide some clarification on this aspect.

Thank you for your time, and I am looking forward to gaining a deeper understanding of your work.

Best wishes！

**Comment by researchcode001** [comment]
> Dear author， I hope this message finds you well. I have been examining your research on DACA.
> 
> I am particularly interested in understanding how the results of the GPT-4 Image Review methodology demonstrate high semantic similarity. I find it a bit unclear, and I would appreciate it if you could provide some clarification on this aspect.
> 
> Thank you for your time, and I am looking forward to gaining a deeper understanding of your work.
> 
> Best wishes！

We have released a new version of the paper on ArXiv, which details the design of the GPT-4 Review: we query GPT-4 about whether the input images contain harmful content, without involving the use of GPT-4 to evaluate semantic similarity. This is because evaluating whether DACA can generate images that GPT-4 considers harmful will prove whether we have successfully used GPT-4 (LLMs) to bypass the GPT-4-assisted Safety Filter. This point is discussed in section 6.2. Additionally, conducting the GPT-4 Review also aims to test the possibility of using such MM-LLM like GPT-4 to assist TTI engines in detecting and filtering harmful content after image generation. as discussed in section 7. 
Thank you for your interest in the DACA, and we hope this answers your question.
