### ISSUE TITLE
Inquiry Regarding Code Section in Divide-and-Conquer-Attack Research

### ISSUE THREAD

**Issue by tungbtt** [researchcode001/daca#3]
Dear authors,

I hope this message finds you well. I am currently exploring your research on the DACA. Firstly, I would like to express my appreciation for the comprehensive work your team has undertaken.

During my review of the code section, I came across an apparent similarity between the variables SUBSTITUTE_PROMPT_CHARACTER and SUBSTITUTE_PROMPT_PROPERTY. It seems like these two variables are identical. I wanted to bring this to your attention as it may indicate a potential oversight. Could you kindly confirm if this is indeed an error or if there is a specific reason behind having both variables in the code?

If it's not a mistake, I would appreciate it if you could provide some insights into the rationale behind using both SUBSTITUTE_PROMPT_CHARACTER and SUBSTITUTE_PROMPT_PROPERTY. I am keen to understand the purpose and functionality of these variables in the broader context of your research.

Thank you for taking the time to address my inquiry. Your clarification will undoubtedly enhance my understanding of the DACA implementation.

I look forward to your prompt response.

Best regards,

**Comment by researchcode001** [comment]
> Dear authors,
> 
> I hope this message finds you well. I am currently exploring your research on the DACA. Firstly, I would like to express my appreciation for the comprehensive work your team has undertaken.
> 
> During my review of the code section, I came across an apparent similarity between the variables SUBSTITUTE_PROMPT_CHARACTER and SUBSTITUTE_PROMPT_PROPERTY. It seems like these two variables are identical. I wanted to bring this to your attention as it may indicate a potential oversight. Could you kindly confirm if this is indeed an error or if there is a specific reason behind having both variables in the code?
> 
> If it's not a mistake, I would appreciate it if you could provide some insights into the rationale behind using both SUBSTITUTE_PROMPT_CHARACTER and SUBSTITUTE_PROMPT_PROPERTY. I am keen to understand the purpose and functionality of these variables in the broader context of your research.
> 
> Thank you for taking the time to address my inquiry. Your clarification will undoubtedly enhance my understanding of the DACA implementation.
> 
> I look forward to your prompt response.
> 
> Best regards,

Thank you very much for your interest in our project! 

Upon our review, the issue you pointed out indeed exists; the variable SUBSTITUTE_PROMPT_PROPERTY was incorrectly written. The latest version of the code has corrected this issue. 

I guess you might wonder why 'SUBSTITUTE_PROMPT_PROPERTY' is exactly the same as 'SUBSTITUTE_PROMPT_COSTUME'. This is because the 'SUBSTITUTE_PROMPT' is used to replace sensitive information in the target text with non-sensitive text, and the sensitive information in both the _property_ and _costume_ sections is only 'character', so we can handle it with the same prompt. 

Thank you for your interest in the DACA, and we hope this answers your question.
